package sd21;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.Enumeration;
import java.util.Scanner;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;





public class stuform extends javax.swing.JFrame {
    String[] values1;String[] values2;String[] values3;String[] values4;String[] values5;
    int count=0;
    Timer t;
    public stuform() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        Qt1 = new javax.swing.JTextField();
        optn1 = new javax.swing.JRadioButton();
        optn2 = new javax.swing.JRadioButton();
        optn4 = new javax.swing.JRadioButton();
        optn3 = new javax.swing.JRadioButton();
        Qt2 = new javax.swing.JTextField();
        optn5 = new javax.swing.JRadioButton();
        optn6 = new javax.swing.JRadioButton();
        optn8 = new javax.swing.JRadioButton();
        optn7 = new javax.swing.JRadioButton();
        optn12 = new javax.swing.JRadioButton();
        optn11 = new javax.swing.JRadioButton();
        Qt3 = new javax.swing.JTextField();
        optn9 = new javax.swing.JRadioButton();
        optn10 = new javax.swing.JRadioButton();
        optn16 = new javax.swing.JRadioButton();
        optn15 = new javax.swing.JRadioButton();
        Qt4 = new javax.swing.JTextField();
        optn13 = new javax.swing.JRadioButton();
        optn14 = new javax.swing.JRadioButton();
        optn17 = new javax.swing.JRadioButton();
        optn20 = new javax.swing.JRadioButton();
        optn19 = new javax.swing.JRadioButton();
        Qt5 = new javax.swing.JTextField();
        optn18 = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        TimerSeconds = new javax.swing.JLabel();
        submitButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Click Here & Get Questions!!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Qt1.setEditable(false);
        Qt1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        buttonGroup1.add(optn1);
        optn1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                optn1ComponentHidden(evt);
            }
        });

        buttonGroup1.add(optn2);

        buttonGroup1.add(optn4);

        buttonGroup1.add(optn3);

        Qt2.setEditable(false);
        Qt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qt2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(optn5);

        buttonGroup2.add(optn6);

        buttonGroup2.add(optn8);

        buttonGroup2.add(optn7);

        buttonGroup3.add(optn12);
        optn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optn12ActionPerformed(evt);
            }
        });

        buttonGroup3.add(optn11);

        Qt3.setEditable(false);

        buttonGroup3.add(optn9);

        buttonGroup3.add(optn10);

        buttonGroup4.add(optn16);

        buttonGroup4.add(optn15);

        Qt4.setEditable(false);

        buttonGroup4.add(optn13);

        buttonGroup4.add(optn14);

        buttonGroup5.add(optn17);
        optn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optn17ActionPerformed(evt);
            }
        });

        buttonGroup5.add(optn20);
        optn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optn20ActionPerformed(evt);
            }
        });

        buttonGroup5.add(optn19);

        Qt5.setEditable(false);

        buttonGroup5.add(optn18);

        submitButton.setBackground(new java.awt.Color(0, 204, 0));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setText("SUBMIT");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        TimerSeconds.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        submitButton1.setBackground(new java.awt.Color(0, 204, 0));
        submitButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton1.setText("Next Page");
        submitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButton1MouseClicked(evt);
            }
        });
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optn9, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(optn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optn10, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(optn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Qt1)
                    .addComponent(Qt2)
                    .addComponent(Qt3)
                    .addComponent(Qt4)
                    .addComponent(Qt5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optn19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(optn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(optn5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(optn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(optn6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(optn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(optn1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(optn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(optn2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(optn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(optn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(optn15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(optn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(optn16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optn17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(optn18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(TimerSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TimerSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(Qt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optn1)
                    .addComponent(optn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optn3)
                    .addComponent(optn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Qt2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optn5)
                    .addComponent(optn6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optn7)
                    .addComponent(optn8))
                .addGap(7, 7, 7)
                .addComponent(Qt3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(optn9)
                    .addComponent(optn10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optn11)
                    .addComponent(optn12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Qt4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optn13)
                    .addComponent(optn14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optn15)
                    .addComponent(optn16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Qt5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optn18)
                    .addComponent(optn17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optn19)
                    .addComponent(optn20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(submitButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   int k=50;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      t=new Timer (1000,new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) 
          {
             TimerSeconds.setText(String.valueOf(k));
             k--;
         
             if(k<0){
             t.stop();
             JOptionPane.showMessageDialog(rootPane,"Your time is over!");
             JOptionPane.showMessageDialog(rootPane,"Submit your answer.");
             }
          }
          }) ; 
       t.start();
          
  
        
        
       String s1=Qt1.getText();
       String s2=Qt2.getText();
       String s3=Qt3.getText();
       String s4=Qt4.getText();
       String s5=Qt5.getText();
       
   
      java.io.File file=new java.io.File("EasyQuestion.txt");
       
       
       try{
           Scanner input=new Scanner(file);
           while(input.hasNext())
           {   
               s1=input.nextLine();
               String[] values1 = s1.split(";");
               Qt1.setText(values1[1]);
               optn1.setText("A."+"   "+values1[2]);
               //optn1.setActionCommand("A."+values1[2]);
               optn2.setText("B."+"   "+values1[3]);
               optn3.setText("C."+"   "+values1[4]);
               optn4.setText("D."+"   "+values1[5]);
               answer1 = values1[6];
               //s1=input.nextLine();
               //Qt1.setText(""+s1 );
               s2=input.nextLine();
               String[] values2 = s2.split(";");
               Qt2.setText(values2[1]);
               optn5.setText("A."+"   "+values2[2]);
               optn6.setText("B."+"   "+values2[3]);
               optn7.setText("C."+"   "+values2[4]);
               optn8.setText("D."+"   "+values2[5]);
               answer2 = values2[6];
              // s2=input.nextLine();
              // Qt2.setText(""+s2 );
              s3=input.nextLine();
              String[] values3 = s3.split(";");
              Qt3.setText(values3[1]);
              optn9.setText("A."+"   "+values3[2]);
              optn10.setText("B."+"   "+values3[3]);
              optn11.setText("C."+"   "+values3[4]);
              optn12.setText("D."+"   "+values3[5]);
              answer3 = values3[6];
               //s3=input.nextLine();
              // Qt3.setText(""+s3 );
              s4=input.nextLine();
              String[] values4 = s4.split(";");
              Qt4.setText(values4[1]);
              optn13.setText("A."+"   "+values4[2]);
              optn14.setText("B."+"   "+values4[3]);
              optn15.setText("C."+"   "+values4[4]);
              optn16.setText("D."+"   "+values4[5]);
              answer4 = values4[6];
               //s4=input.nextLine();
               //Qt4.setText(""+s4 );
               s5=input.nextLine();
               String[] values5 = s5.split(";");
               Qt5.setText(values5[1]);
               optn17.setText("A."+"   "+values5[2]);
               optn18.setText("B."+"   "+values5[3]);
               optn19.setText("C."+"   "+values5[4]);
               optn20.setText("D."+"   "+values5[5]);
               answer5 = values5[6];
               //s5=input.nextLine();
              // Qt5.setText(""+s5 );
               
           }
       }catch(FileNotFoundException e)
       {
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Qt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qt2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
              
    Enumeration elements = buttonGroup1.getElements();
    while (elements.hasMoreElements()) {
      AbstractButton button = (AbstractButton)elements.nextElement();
      if (button.isSelected()) {
        System.out.println( button.getText());
        if(button.getText().startsWith(answer1))
            count++;
      }
    }
    
    elements = buttonGroup2.getElements();
    while (elements.hasMoreElements()) {
      AbstractButton button = (AbstractButton)elements.nextElement();
      if (button.isSelected()) {
        System.out.println( button.getText());
        if(button.getText().startsWith(answer2))
            count++;
      }
    }
    
    elements = buttonGroup3.getElements();
    while (elements.hasMoreElements()) {
      AbstractButton button = (AbstractButton)elements.nextElement();
      if (button.isSelected()) {
        System.out.println( button.getText());
        if(button.getText().startsWith(answer3))
            count++;
      }
    }
    
    elements = buttonGroup4.getElements();
    while (elements.hasMoreElements()) {
      AbstractButton button = (AbstractButton)elements.nextElement();
      if (button.isSelected()) {
        System.out.println( button.getText());
        if(button.getText().startsWith(answer4))
            count++;
      }
    }
    
    elements = buttonGroup5.getElements();
    while (elements.hasMoreElements()) {
      AbstractButton button = (AbstractButton)elements.nextElement();
      if (button.isSelected()) {
        System.out.println( button.getText());
        if(button.getText().startsWith(answer5))
            count++;
      }
    }
    System.out.println(count);
    if(optn1.isSelected()||optn2.isSelected()||optn3.isSelected()||optn4.isSelected()||optn5.isSelected()||optn6.isSelected()||optn7.isSelected()||optn8.isSelected()||optn9.isSelected()||optn10.isSelected()||optn11.isSelected()||optn12.isSelected()||optn13.isSelected()||optn14.isSelected()||optn15.isSelected()||optn16.isSelected()||optn17.isSelected()||optn18.isSelected()||optn19.isSelected()||optn20.isSelected()){
       t.stop();
        JOptionPane.showMessageDialog(null,"You have scored ... " +count +"\nCorrect answers are :"+" \n1."+answer1+ "\n2."+answer2+ "\n3."+answer3+ "\n4."+answer4+ "\n5."+answer5);
    }
    
    else{
        t.stop();
         JOptionPane.showMessageDialog(null,"You have to select from the options for all questions ." );
    }
    t.start();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void optn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optn12ActionPerformed

    private void optn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optn20ActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonMouseClicked

    private void optn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optn17ActionPerformed

    private void optn1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_optn1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_optn1ComponentHidden

    private void submitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButton1MouseClicked

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stuform().setVisible(true);
            }
        });
    }

    
    String answer1,answer2,answer3,answer4,answer5;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Qt1;
    private javax.swing.JTextField Qt2;
    private javax.swing.JTextField Qt3;
    private javax.swing.JTextField Qt4;
    private javax.swing.JTextField Qt5;
    private javax.swing.JLabel TimerSeconds;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton optn1;
    private javax.swing.JRadioButton optn10;
    private javax.swing.JRadioButton optn11;
    private javax.swing.JRadioButton optn12;
    private javax.swing.JRadioButton optn13;
    private javax.swing.JRadioButton optn14;
    private javax.swing.JRadioButton optn15;
    private javax.swing.JRadioButton optn16;
    private javax.swing.JRadioButton optn17;
    private javax.swing.JRadioButton optn18;
    private javax.swing.JRadioButton optn19;
    private javax.swing.JRadioButton optn2;
    private javax.swing.JRadioButton optn20;
    private javax.swing.JRadioButton optn3;
    private javax.swing.JRadioButton optn4;
    private javax.swing.JRadioButton optn5;
    private javax.swing.JRadioButton optn6;
    private javax.swing.JRadioButton optn7;
    private javax.swing.JRadioButton optn8;
    private javax.swing.JRadioButton optn9;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
}
